# Generated by Django 4.1.3 on 2022-11-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiForm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='senha',
            new_name='password',
        ),
    ]
